core:
  replicas: 3
  resources:
    requests:
      cpu: 250m
      memory: 512Mi

replicant:
  replicas: 7
  resources:
    requests:
      cpu: 250m
      memory: 1Gi

service:
  dashboard:
    spec:
      type: LoadBalancer
  listeners:
    spec:
      type: LoadBalancer
