apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: {{ .Release.Namespace }}
spec:
  image: emqx:5.1
  coreTemplate:
    spec:
      replicas: {{ .Values.core.replicas }}
      resources:
{{ toYaml .Values.core.resources | indent 8 }}
  replicantTemplate:
    spec:
      replicas: {{ .Values.replicant.replicas }}
      resources:
{{ toYaml .Values.replicant.resources | indent 8 }}
  dashboardServiceTemplate:
    spec:
{{ toYaml .Values.service.dashboard.spec | indent 6 }}
  listenersServiceTemplate:
    spec:
{{ toYaml .Values.service.listeners.spec | indent 6 }}
